### ISSUE TITLE
New state of the arts for CIFAR <-> STL and VisDA

### ISSUE THREAD

**Issue by cnyanhao** [Britefury/self-ensemble-visual-domain-adapt#8]
Great work, again :) 
I've noticed that your work has been the state of the art, especially for the digits classification. But the performances for the CIFAR <-> STL seem to be improved. I'm wondering whether you've noticed any recent works for the non-digits tasks. If any, please share with us. Thank you very much:)

**Comment by cnyanhao** [comment]
On the other hand, do you think domain adaptation will be efficient for the detection tasks? I've found two papers concerning this:

_Cross-Domain Weakly-Supervised Object Detection through Progressive Domain Adaptation
Domain Adaptive Faster R-CNN for Object Detection in the Wild_

Have you found other works about applying domain adaptation to object detection? If any, please share with us. Thank you very much:)

**Comment by Britefury** [comment]
Sorry for the late reply.

I must admit I haven't been following the field as closely since early 2018.

Thanks for pointing out those papers; they are very interesting!

I did participate in the VisDa 2018 object detection domain adaptation challenge and got 2nd place with an algorithm that is related to the work here. Still working on the publication.

The 1st place approach is pretty interesting.

https://ai.bu.edu/visda-2018/
